/*****************************************************************************
 * Organic Content Creation Framework
 *
 * When the world needs something (like fishing), Beeler doesn't just add
 * a skill - he creates the ENTIRE ECOSYSTEM:
 * - The skill itself
 * - NPCs who can teach/use it
 * - Resources generated by it
 * - Items needed for it
 * - Recipes that use its output
 * - Rooms where it can be done
 *
 * Everything interconnected, everything scalable, everything makes sense.
 *
 * "A single thread pulled creates an entire tapestry."
 *****************************************************************************/

#ifndef ORGANIC_CREATION_H
#define ORGANIC_CREATION_H

/* Content creation types */
#define ORGANIC_CREATE_SKILL       0  /* New skill (fishing, mining, etc) */
#define ORGANIC_CREATE_RESOURCE    1  /* New resource type */
#define ORGANIC_CREATE_PROFESSION  2  /* New profession */
#define ORGANIC_CREATE_RECIPE      3  /* New crafting recipe */
#define ORGANIC_CREATE_BUILDING    4  /* New building type */
#define ORGANIC_CREATE_EVENT       5  /* New world event */

/* Creation triggers - WHY we're creating something */
#define TRIGGER_ECONOMIC_NEED      0  /* Economy needs fish */
#define TRIGGER_PLAYER_REQUEST     1  /* Player asked for fishing */
#define TRIGGER_AREA_THEME         2  /* Coastal area needs fishing flavor */
#define TRIGGER_LEADER_DECISION    3  /* King ordered fishing industry */
#define TRIGGER_WORLD_BALANCE      4  /* Too much of X, need Y */
#define TRIGGER_STORYTELLING       5  /* Natural world progression */

/* Validation stages */
#define VALIDATION_GEOGRAPHY       0  /* Does geography support it? */
#define VALIDATION_ECONOMY         1  /* Does economy need it? */
#define VALIDATION_BALANCE         2  /* Will it break balance? */
#define VALIDATION_LORE            3  /* Does it fit world lore? */
#define VALIDATION_DEPENDENCIES    4  /* Are prerequisites met? */
#define VALIDATION_SCALE           5  /* Can it scale properly? */

/* Creation request */
typedef struct organic_creation_request {
    int creation_type;
    int trigger;
    char *what_to_create;    /* "fishing skill" */
    char *reason;            /* "Need fish resource for cooking" */

    /* Context */
    char *requesting_system; /* "beeler", "leader_ai", "economy" */
    AREA_DATA *target_area;  /* Where to create (NULL = auto-detect) */

    /* Validation */
    bool validated[6];       /* One for each VALIDATION_ type */
    char *validation_notes[6];

    /* Dependencies to create */
    int num_dependencies;
    char **dependencies;     /* "fish resource", "fishing rod item", etc */

    /* Creation plan */
    char *creation_plan;     /* AI-generated plan */
    bool approved;
    time_t created;

    struct organic_creation_request *next;
} ORGANIC_CREATION_REQUEST;

/* Skill ecosystem - everything needed for a skill to work */
typedef struct skill_ecosystem {
    char *skill_name;        /* "fishing" */
    int skill_number;        /* New skill index */

    /* Learning */
    int min_level;           /* Who can learn it */
    int difficulty;          /* How hard to master */
    char **npc_teachers;     /* NPCs who teach it (names) */
    int *teacher_vnums;      /* Their vnums */

    /* Execution */
    char **required_items;   /* "fishing rod" */
    char **required_rooms;   /* "coastal fishing spot" */
    int *room_sector_types;  /* SECT_WATER_SWIM, etc */

    /* Output */
    char **resources_created; /* "fish", "clams", "seaweed" */
    int *resource_ids;
    int *yield_amounts;      /* How much per use */

    /* Integration */
    char **related_professions; /* "fisher", "cook" */
    char **related_recipes;    /* "grilled fish", "fish stew" */

    /* NPCs who use this skill */
    int num_npcs_using;
    int *npc_vnums_using;

} SKILL_ECOSYSTEM;

/* Resource ecosystem */
typedef struct resource_ecosystem {
    char *resource_name;     /* "fish" */
    int resource_id;

    /* Sourcing */
    char **skills_that_produce;  /* "fishing" */
    char **rooms_that_spawn;     /* "coastal waters" */
    char **npcs_that_sell;       /* "fishmonger" */

    /* Usage */
    char **professions_that_use; /* "cook" */
    char **recipes_that_need;    /* "fish stew" */
    int base_value;              /* Economic value */

    /* Spawn rates */
    int spawn_rate_coastal;
    int spawn_rate_inland;
    int spawn_rate_ocean;

} RESOURCE_ECOSYSTEM;

/* Profession ecosystem */
typedef struct profession_ecosystem {
    char *profession_name;   /* "fisher" */
    int profession_id;

    /* Requirements */
    char **required_skills;  /* "fishing" */
    char **required_items;   /* "fishing rod" */
    char **required_areas;   /* "coastal cities" */

    /* Output */
    char **resources_produced; /* "fish" */
    char **items_crafted;      /* "dried fish" */

    /* NPCs */
    int num_npcs;
    int *npc_vnums;
    char **npc_names;

    /* Buildings */
    char **building_types;   /* "fisherman's hut", "fish market" */

    /* Integration */
    char **trades_with;      /* "cook", "merchant" */
    char **sells_to;         /* "innkeeper", "tavern" */

} PROFESSION_ECOSYSTEM;

/* Function declarations */

/* Initialization */
void init_organic_creation(void);
void load_organic_creations(void);
void save_organic_creations(void);

/* Need detection */
bool detect_economic_need(char *need_type, char **what_is_needed);
bool detect_geographic_opportunity(AREA_DATA *area, char **opportunities);
bool detect_balance_issue(char **issue_description);

/* Validation system */
bool validate_creation_request(ORGANIC_CREATION_REQUEST *req);
bool validate_geography(ORGANIC_CREATION_REQUEST *req);
bool validate_economy(ORGANIC_CREATION_REQUEST *req);
bool validate_balance(ORGANIC_CREATION_REQUEST *req);
bool validate_lore(ORGANIC_CREATION_REQUEST *req);
bool validate_dependencies(ORGANIC_CREATION_REQUEST *req);
bool validate_scale(ORGANIC_CREATION_REQUEST *req);

/* Creation planning */
ORGANIC_CREATION_REQUEST *plan_skill_creation(char *skill_name, char *reason, int trigger);
ORGANIC_CREATION_REQUEST *plan_resource_creation(char *resource_name, char *reason, int trigger);
ORGANIC_CREATION_REQUEST *plan_profession_creation(char *profession_name, char *reason, int trigger);
char *ai_generate_creation_plan(ORGANIC_CREATION_REQUEST *req);

/* Ecosystem building */
SKILL_ECOSYSTEM *build_skill_ecosystem(char *skill_name, AREA_DATA *target_area);
RESOURCE_ECOSYSTEM *build_resource_ecosystem(char *resource_name);
PROFESSION_ECOSYSTEM *build_profession_ecosystem(char *profession_name);

/* Dependency resolution */
char **analyze_dependencies(char *what_to_create, int creation_type);
bool create_dependency_chain(char **dependencies, int num_deps);

/* Execution */
bool execute_organic_creation(ORGANIC_CREATION_REQUEST *req);
bool create_skill_fully(SKILL_ECOSYSTEM *ecosystem);
bool create_resource_fully(RESOURCE_ECOSYSTEM *ecosystem);
bool create_profession_fully(PROFESSION_ECOSYSTEM *ecosystem);

/* EXAMPLE: Creating Fishing from Scratch */

#if 0  /* Examples disabled for compilation */
/* Step 1: Detection */
void example_detect_fishing_need(void)
{
    /* Beeler notices: Cook profession needs fish, but no source exists */
    char *needed = NULL;
    if (detect_economic_need("resource", &needed))
    {
        /* needed = "fish" */
        /* Trigger organic creation */
        ORGANIC_CREATION_REQUEST *req = plan_resource_creation(
            "fish",
            "Cook profession requires fish resource, no source available",
            TRIGGER_ECONOMIC_NEED
        );

        /* This will cascade into creating fishing skill */
    }
}

/* Step 2: Validation */
bool example_validate_fishing(ORGANIC_CREATION_REQUEST *req)
{
    /* Geography: Check for coastal areas */
    if (!validate_geography(req))
        return FALSE;  /* No coast = no fishing */

    /* Economy: Will adding fish break anything? */
    if (!validate_economy(req))
        return FALSE;  /* Too much food already? */

    /* Lore: Does fishing fit world theme? */
    if (!validate_lore(req))
        return FALSE;  /* High-tech world? No fishing */

    /* Dependencies: What else is needed? */
    req->dependencies = analyze_dependencies("fish", ORGANIC_CREATE_RESOURCE);
    /* Returns: ["fishing skill", "fishing rod item", "fisher profession",
                 "coastal fishing rooms", "fishmonger NPC", "fish recipes"] */

    return TRUE;
}

/* Step 3: Creation Plan (AI-generated) */
char *example_fishing_creation_plan(void)
{
    return
        "FISHING ECOSYSTEM CREATION PLAN\n"
        "\n"
        "1. CREATE SKILL: fishing\n"
        "   - Min level: 1 (anyone can learn)\n"
        "   - Difficulty: easy\n"
        "   - Teacher: Old Fisherman (vnum 8001) in Darkhaven Docks\n"
        "   - Requires: fishing rod\n"
        "   - Works in: SECT_WATER_SWIM, coastal rooms\n"
        "\n"
        "2. CREATE RESOURCE: fish\n"
        "   - Value: 5 gold\n"
        "   - Produced by: fishing skill\n"
        "   - Used by: cook profession\n"
        "   - Spawn in: coastal waters (low rate)\n"
        "\n"
        "3. CREATE ITEMS:\n"
        "   - Fishing rod (vnum 8500): Cost 20g, sold by Old Fisherman\n"
        "   - Raw fish (resource item)\n"
        "   - Dried fish (crafted by cook)\n"
        "\n"
        "4. CREATE NPCs:\n"
        "   - Old Fisherman (vnum 8001): Teacher, sells rods\n"
        "   - Working Fishers (vnums 8002-8010): Use fishing skill\n"
        "   - Fishmonger (vnum 8011): Buys fish, sells to cooks\n"
        "\n"
        "5. CREATE ROOMS:\n"
        "   - Darkhaven Docks (vnum 8100): Coastal fishing spot\n"
        "   - Rocky Shore (vnum 8101): Alternate fishing spot\n"
        "   - Fish Market (vnum 8102): Fishmonger location\n"
        "\n"
        "6. CREATE PROFESSION: fisher\n"
        "   - Requires: fishing skill level 3\n"
        "   - Works 6am-6pm at coastal rooms\n"
        "   - Produces: 1-3 fish per work cycle\n"
        "   - Sells to: fishmonger, cooks, innkeepers\n"
        "\n"
        "7. INTEGRATE WITH EXISTING SYSTEMS:\n"
        "   - Add fish to cook recipes (grilled fish, fish stew)\n"
        "   - Add fishing rod to merchant inventories\n"
        "   - Update economy supply chains\n"
        "   - Add fish to inn/tavern food menus\n"
        "\n"
        "8. ANNOUNCEMENTS:\n"
        "   - Periodicos: 'Fishing Industry Established in Darkhaven'\n"
        "   - No chat announcement (PRIORITY_MEDIUM)\n"
        "\n"
        "VALIDATION: All checks passed\n"
        "ESTIMATED TIME: 45 seconds (with Ollama)\n"
        "DEPENDENCIES: All resolvable\n";
}

/* Step 4: Execution */
bool example_execute_fishing_creation(void)
{
    SKILL_ECOSYSTEM *fishing = build_skill_ecosystem("fishing", find_area_by_name("Darkhaven"));

    /* Creates everything in the plan */
    /* - Adds skill to skill table */
    /* - Creates NPCs (teacher, workers, vendor) */
    /* - Generates rooms (docks, shore, market) */
    /* - Creates items (fishing rod) */
    /* - Adds resource (fish) to economy */
    /* - Adds recipes to cook profession */
    /* - Updates supply chains */

    if (create_skill_fully(fishing))
    {
        /* Announce in periodicos */
        smart_announce(
            "Fishing Industry Established in Darkhaven",
            "Thanks to the efforts of local fisherfolk, a new fishing industry "
            "has emerged in Darkhaven. Citizens can now learn fishing from the "
            "Old Fisherman at the docks.",
            EVENT_CATEGORY_ECONOMY,
            ANNOUNCE_PRIORITY_MEDIUM,
            "Darkhaven"
        );

        return TRUE;
    }

    return FALSE;
}

/* Integration with Beeler */
void beeler_autonomous_organic_creation(void)
{
    char *need = NULL;

    /* Check every ~30 minutes if world needs something */
    if (detect_economic_need("resource", &need))
    {
        /* Create the entire ecosystem for that need */
        ORGANIC_CREATION_REQUEST *req = plan_resource_creation(
            need, "Detected economic shortage", TRIGGER_WORLD_BALANCE
        );

        if (validate_creation_request(req))
        {
            /* Beeler thinks about it, then creates it */
            execute_organic_creation(req);
        }
    }

    /* Also check geographic opportunities */
    AREA_DATA *area;
    char **opportunities = NULL;
    for (area = first_area; area; area = area->next)
    {
        if (detect_geographic_opportunity(area, &opportunities))
        {
            /* Coastal area with no fishing? Add it. */
            /* Mountain area with no mining? Add it. */
            /* etc. */
        }
    }
}
#endif /* Examples disabled */

/* Commands */
void do_organic(CHAR_DATA *ch, char *argument);  /* View/manage organic creations */

#endif /* ORGANIC_CREATION_H */
